// ONLY WAY FOR TREE SHAKING
export { default as identical } from 'ramda/src/identical'
export { default as pipe } from 'ramda/src/pipe'
export { default as replace } from 'ramda/src/replace'
export { default as is } from 'ramda/src/is'
export { default as find } from 'ramda/src/find'
export { default as reduce } from 'ramda/src/reduce'
export { default as filter } from 'ramda/src/filter'
export { default as length } from 'ramda/src/length'
export { default as gt } from 'ramda/src/gt'
export { default as slice } from 'ramda/src/slice'
export { default as split } from 'ramda/src/split'
export { default as cond } from 'ramda/src/cond'
export { default as T } from 'ramda/src/T'
export { default as isEmpty } from 'ramda/src/isEmpty'
export { default as isNil } from 'ramda/src/isNil'
export { default as always } from 'ramda/src/always'
